# Generated by Django 3.0.3 on 2020-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_auto_20200401_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date_available', models.DateField()),
            ],
        ),
    ]
